[project]
name = "dbt-artifacts-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gary Yiu", email = "yiucheukpuigary@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.5",
]

[project.scripts]
dbt-artifacts-api = "dbt_artifacts_api:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[tool.mypy]
strict = true

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
